import type { EvidenceSourceDefinition } from "../../domain.js";

const verifiedOn = "2026-08-28";

export const importSources = {
  foreignTradePolicy: {
    id: "dgft-ftp-2023",
    title: "Foreign Trade Policy 2023",
    issuer: "Directorate General of Foreign Trade",
    url: "https://content.dgft.gov.in/Website/dgftprod/61d61bc2-272e-4880-b96c-c8f685a3b244/Foreign%20Trade%20Policy%202023.pdf",
    official: true,
    tier: "operative-instrument",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
    locator: "Paragraphs 2.05 and 2.06",
  },
  iecManual: {
    id: "dgft-iec-manual-v4-1",
    title: "IEC Module User Help File, version 4.1",
    issuer: "Directorate General of Foreign Trade",
    url: "https://content.dgft.gov.in/Website/IEC_Manual_V4.1.pdf",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
    locator: "Updated February 2026",
  },
  importTradeGuide: {
    id: "icegate-i4c-import-trade-guide",
    title: "Trade Guide on Imports",
    issuer: "Indian Customs Electronic Gateway",
    url: "https://www.icegate.gov.in/Webappl/Trade-Guide-on-Imports",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  icegateRegistration: {
    id: "icegate-registration-faq",
    title: "ICEGATE Registration FAQ",
    issuer: "Indian Customs Electronic Gateway",
    url: "https://www.icegate.gov.in/sites/default/files/2023-12/Registration-FAQ%20%281%29.pdf",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  eSanchit: {
    id: "icegate-esanchit-advisory",
    title: "e-Sanchit process guides and advisory",
    issuer: "Indian Customs Electronic Gateway",
    url: "https://www.icegate.gov.in/guidelines/esanchit-advisory",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  customsSingleWindow: {
    id: "cbic-swift-circular-03-2016",
    title: "Customs Single Window and integrated declaration circular",
    issuer: "Central Board of Indirect Taxes and Customs",
    url: "https://www.icegate.gov.in/sites/default/files/2024-01/circ03-2016cs.pdf",
    official: true,
    tier: "operative-instrument",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
    locator: "PGA reference and release requirements",
  },
  bisCrs: {
    id: "bis-scheme-ii-product-list",
    title: "Products under Compulsory Certification — Scheme II",
    issuer: "Bureau of Indian Standards",
    url: "https://www.bis.gov.in/product-certification/products-under-compulsory-certification/scheme-ii-registration-scheme/?lang=en",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
    locator: "Wireless Headphone and Earphone",
  },
  wpcEta: {
    id: "dot-wpc-eta",
    title: "Equipment Type Approval through self-declaration",
    issuer: "Department of Telecommunications",
    url: "https://eservices.dot.gov.in/equipment-type-approval-eta",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  batteryRules: {
    id: "cpcb-battery-waste-rules-2022",
    title: "Battery Waste Management Rules, 2022",
    issuer: "Central Pollution Control Board",
    url: "https://cpcb.nic.in/uploads/hwmd/Battery-WasteManagementRules-2022.pdf",
    official: true,
    tier: "law",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  eWasteFaq: {
    id: "cpcb-ewaste-faq",
    title: "Frequently Asked Questions on E-Waste Management Rules, 2022",
    issuer: "Central Pollution Control Board",
    url: "https://cpcb.nic.in/uploads/Projects/E-Waste/FAQ_ewaste_23012024.pdf",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  plasticEpr: {
    id: "cpcb-plastic-epr-portal",
    title: "Centralised EPR Portal for Plastic Packaging",
    issuer: "Central Pollution Control Board",
    url: "https://eprplastic.cpcb.gov.in/",
    official: true,
    tier: "service-owner",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  legalMetrologyRules: {
    id: "consumer-affairs-lmpc-rules",
    title: "Legal Metrology (Packaged Commodities) Rules with amendments",
    issuer: "Department of Consumer Affairs",
    url: "https://consumeraffairs.nic.in/sites/default/files/file-uploads/latestnews/LM_PCR_All_Amendements.pdf",
    official: true,
    tier: "law",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
  rbiImportDirection: {
    id: "rbi-import-master-direction",
    title: "Master Direction — Import of Goods and Services",
    issuer: "Reserve Bank of India",
    url: "https://systemhealth.rbi.org.in/Scripts/BS_ViewMasDirections.aspx_id%3D10201%281%29.html",
    official: true,
    tier: "operative-instrument",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
    locator: "Updated 29 August 2024",
  },
  gstInputCredit: {
    id: "cbic-input-tax-credit-rules",
    title: "Input Tax Credit Rules",
    issuer: "Central Board of Indirect Taxes and Customs",
    url: "https://cbic-gst.gov.in/input-tax-credit-rules.html",
    official: true,
    tier: "law",
    jurisdiction: { countryCode: "IN", level: "central" },
    retrievedOn: verifiedOn,
  },
} as const satisfies Record<string, EvidenceSourceDefinition>;
